//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string Type { get; set; }
        public double Size { get; set; }
        public string Subject { get; set; }
        public string Availability { get; set; }
        public string FileUrl { get; set; }
    
        public virtual User User { get; set; }
    }
}
